# docker-compose.yml
version: "3.8"

services:
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - 3000

volumes:
  grafana-data:
